version: '3'

services:
  postgres:
    image: 'postgres:12'
    restart: always
    container_name: 'postgres'
    environment:
      - 'POSTGRES_DB='
      - 'POSTGRES_USER='
      - 'POSTGRES_PASSWORD='

  app:
    build: ./
    container_name: 'cryptobot'
    ports:
      - "8081:8081"
